### ISSUE TITLE
IllegalStateException: on multiple properties clashing after sanitization

### ISSUE THREAD

**Issue by andreaTP** [sundrio/sundrio#470]
Reproducer.

With a `pom.xml`:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>io.repro</groupId>
    <artifactId>repro-sundrio</artifactId>
    <version>0.0.1</version>

    <packaging>jar</packaging>

    <name>Repro</name>
    
    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <fabric8.version>6.12.0</fabric8.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.fabric8</groupId>
                <artifactId>kubernetes-client-bom-with-deps</artifactId>
                <version>${fabric8.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>io.fabric8</groupId>
            <artifactId>openshift-client</artifactId>
        </dependency>
        <dependency>
            <groupId>io.fabric8</groupId>
            <artifactId>kubernetes-model</artifactId>
        </dependency>
        <dependency>
            <groupId>io.fabric8</groupId>
            <artifactId>generator-annotations</artifactId>
        </dependency>
        <dependency>
            <groupId>io.sundr</groupId>
            <artifactId>builder-annotations</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>io.fabric8</groupId>
                <artifactId>java-generator-maven-plugin</artifactId>
                <version>${fabric8.version}</version>
                <executions>
                    <execution>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <source>repro.yaml</source>
                    <extraAnnotations>true</extraAnnotations>
                    <alwaysPreserveUnknown>true</alwaysPreserveUnknown>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
```

and a CRD like:

```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dummies.example.com
spec:
  group: example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                # Generated by Kubebuilder: https://github.com/prometheus-operator/prometheus-operator/blob/1d3fa6335a6a3e98c16a7723073a0d6529793526/pkg/apis/monitoring/v1/prometheus_types.go#L824
                action:
                  default: replace
                  description: Action to perform based on regex matching.
                    Default is 'replace'. uppercase and lowercase actions
                    require Prometheus >= 2.36.
                  enum:
                  - replace
                  - Replace
                  - keep
                  - Keep
                  - drop
                  - Drop
                  - hashmod
                  - HashMod
                  - labelmap
                  - LabelMap
                  - labeldrop
                  - LabelDrop
                  - labelkeep
                  - LabelKeep
                  - lowercase
                  - Lowercase
                  - uppercase
                  - Uppercase
                  type: string
  scope: Namespaced
  names:
    plural: dummies
    singular: dummy
    kind: Dummy
```

`sundrio` give up with the following exception:

```
java.lang.IllegalStateException: Found multiple properties in: Action that map to: REPLACE. Properties: _REPLACE and REPLACE!
```

I agree that the definition does not show great API design, but it's in the Prometheus Operator and it would be nice to support it somehow.
