### ISSUE TITLE
Duplicated property from generated class

### ISSUE THREAD

**Issue by heruan** [sundrio/sundrio#488]
I'm generating class files with Fabric8 (7.0.1) from the CloudNativePG CRDs. When Sundrio's processes annotations, it fails with:
```
java.lang.IllegalStateException: Found multiple properties in: Action that map to: replace. Properties: Replace and replace!
        at io.sundr.builder.internal.checks.DublicatePropertyCheck.visit(DublicatePropertyCheck.java:28)
```

I assume this is related to this part of the CRD:
```yaml
                      items:
                        description: |-
                          RelabelConfig allows dynamic rewriting of the label set for targets, alerts,
                          scraped samples and remote write samples.
                          
                          More info: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config
                        properties:
                          action:
                            default: replace
                            description: |-
                              Action to perform based on the regex matching.
                              
                              `Uppercase` and `Lowercase` actions require Prometheus >= v2.36.0.
                              `DropEqual` and `KeepEqual` actions require Prometheus >= v2.41.0.
                              
                              Default: "Replace"
                            enum:
                              - replace
                              - Replace
                              - keep
                              - Keep
                              - drop
                              - Drop
```

But I cannot change the CRD nor the generated classes (I've tried setting Fabric8 generator's `uppercaseEnums` both to true and false, same error).

Is it possible for the annotation processor to ignore duplicates?
